
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: capx
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: '%'
      TZ: UTC
    command: 
      - --default-authentication-plugin=caching_sha2_password
    ports:
      - "3307:3306"
    networks:
      - capx-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/capx
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      TZ: UTC
    depends_on:
      db:
        condition: service_healthy
    networks:
      - capx-network
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh  
    command: ["sh", "/wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]

networks:
  capx-network:
    driver: bridge

volumes:
  mysql-data: